# Generated by Django 3.1.3 on 2020-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_genre_subgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='summary',
            field=models.TextField(default=1, help_text='Ingrese un breve descripción del género.', max_length=1000),
            preserve_default=False,
        ),
    ]
