# Generated by Django 3.1.3 on 2020-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_genre_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='subgenre',
            field=models.CharField(default=1, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubGenre',
        ),
    ]
