# Generated by Django 3.1.3 on 2020-12-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201209_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_see_buttons', 'Pueden modificar los Autores'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Puede renovar la fecha de devolución'),)},
        ),
    ]
