# Generated by Django 3.1.3 on 2020-12-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201210_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_see_buttons', 'Pueden modificar los Libros'),)},
        ),
    ]
